name: Build Flutter APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Create Android Platform Files
        run: |
          mkdir temp_app
          cd temp_app
          flutter create --org com.mehrab.app --project-name mehrab .
          rm -rf lib pubspec.yaml
          cd ..
          cp -r temp_app/. .
          rm -rf temp_app

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mehrab-app-release
          path: build/app/outputs/flutter-apk/app-release.apk
